theme: jekyll-theme-cayman

title: Attributes-Aware Deep Music Transformation
description: Lisa Kawai (The University of Tokyo), Philippe Esling (IRCAM), and Tatsuya Harada (The University of Tokyo, RIKEN)